# -*- coding: utf-8 -*-
"""Pinecone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRy-UG2-E0a8mq2Ylog0JjgQEaskNnGD
"""

!pip install -U pinecone openai pypdf python-dotenv sentence-transformers

from sentence_transformers import SentenceTransformer
from pinecone import Pinecone, ServerlessSpec
import os

pinecone_api_key = "pcsk_799t7n_4VkNbywQux2b9UyYsmuCBs5qJde9NQUrUKhWHq86o4NRqhCbHyKBz8ZgVYyFmaC"

index_name = "resume-ranking"

pc = Pinecone(api_key=pinecone_api_key)

existing_indexes = [index["name"] for index in pc.list_indexes()]

print(existing_indexes)

model=SentenceTransformer('all-MiniLM-L6-v2')
model.get_sentence_embedding_dimension()

pc=Pinecone(api_key=pinecone_api_key)
existing_indexes = [index["name"] for index in pc.list_indexes()]

existing_indexes

if index_name not in existing_indexes:
  pc.create_index(name=index_name,dimension=384,metric="cosine",
                  spec=ServerlessSpec(cloud="aws",region="us-east-1"))
index=pc.Index(index_name)

resumes = [

    {
        "id": "resume_1",
        "name": "Rahul Sharma",
        "text": """
        Rahul Sharma is a Data Scientist with 2 years of experience.
        Skilled in Python, Pandas, NumPy, Scikit-learn, SQL,
        Machine Learning, Deep Learning and Natural Language Processing.
        Experienced in building classification, regression and clustering
        models. Worked with Random Forest, Logistic Regression, XGBoost,
        CNN and NLP models. Experience with data preprocessing,
        exploratory data analysis, feature engineering and model evaluation.
        """
    },

    {
        "id": "resume_2",
        "name": "Priya Singh",
        "text": """
        Priya Singh is a Software Developer with 3 years of experience.
        Strong knowledge of Java, Spring Boot, REST APIs, MySQL,
        Git and Docker. Experienced in backend application development,
        microservices and database management. Familiar with AWS and
        CI/CD pipelines.
        """
    },

    {
        "id": "resume_3",
        "name": "Vilas Kumar",
        "text": """
        Vilas Kumar is an AI and Machine Learning graduate with skills
        in Python, Machine Learning, Deep Learning, SQL, Pandas,
        NumPy and Scikit-learn. Worked on machine learning projects
        involving data preprocessing, exploratory data analysis,
        feature engineering, model training and evaluation.
        Experience with NLP, Generative AI, RAG, embeddings,
        vector databases and MLflow.
        """
    },

    {
        "id": "resume_4",
        "name": "Arjun Patel",
        "text": """
        Arjun Patel is a Data Analyst with 2 years of experience.
        Skilled in SQL, Excel, Power BI, Tableau, Python and Pandas.
        Experienced in dashboard creation, business reporting,
        data visualization, KPI analysis and exploratory data analysis.
        Strong analytical and communication skills.
        """
    },

    {
        "id": "resume_5",
        "name": "Sneha Reddy",
        "text": """
        Sneha Reddy is a Machine Learning Engineer with 3 years
        of experience. Skilled in Python, TensorFlow, PyTorch,
        Scikit-learn, NLP, Computer Vision and Deep Learning.
        Developed neural networks, image classification systems
        and NLP applications. Experience deploying ML models
        using Docker and cloud platforms.
        """
    },

    {
        "id": "resume_6",
        "name": "Karthik Rao",
        "text": """
        Karthik Rao is a Cloud Engineer with 4 years of experience.
        Skilled in AWS, EC2, S3, Lambda, Docker, Kubernetes,
        Terraform and Linux. Experienced in cloud infrastructure,
        deployment automation, monitoring and CI/CD pipelines.
        Strong knowledge of DevOps practices.
        """
    },

    {
        "id": "resume_7",
        "name": "Ananya Gupta",
        "text": """
        Ananya Gupta is a Data Scientist with 1 year of experience.
        Skilled in Python, SQL, Pandas, NumPy, Scikit-learn,
        Machine Learning and statistics. Worked on predictive
        modeling, customer segmentation, regression and classification.
        Experienced in data cleaning, feature engineering and
        model performance evaluation.
        """
    },

    {
        "id": "resume_8",
        "name": "Rohan Mehta",
        "text": """
        Rohan Mehta is a Frontend Developer with 2 years of experience.
        Skilled in HTML, CSS, JavaScript, React.js, Next.js and Git.
        Experienced in building responsive web applications,
        reusable UI components and REST API integrations.
        Strong understanding of frontend development.
        """
    },

    {
        "id": "resume_9",
        "name": "Meera Nair",
        "text": """
        Meera Nair is an AI Engineer with 2 years of experience.
        Skilled in Python, Machine Learning, Deep Learning,
        Generative AI, Large Language Models, NLP, RAG,
        vector databases and embeddings. Built AI applications
        using LangChain, Hugging Face and transformer models.
        Experience with prompt engineering and semantic search.
        """
    },

    {
        "id": "resume_10",
        "name": "Aditya Verma",
        "text": """
        Aditya Verma is a Business Analyst with 3 years of experience.
        Skilled in SQL, Excel, Power BI, business analysis,
        requirements gathering, stakeholder management and
        data visualization. Experienced in analyzing business
        requirements and creating dashboards and reports.
        """
    }
]

vectors=[]
for resume in resumes:

    embedding = model.encode(
        resume["text"]
    ).tolist()

    vectors.append({
        "id": resume["id"],
        "values": embedding,
        "metadata": {
            "name": resume["name"],
            "resume_text": resume["text"]
        }
    })

vectors[0]

job_description = """
We are looking for a Data Scientist.

The candidate should have strong knowledge of Python,
Machine Learning, SQL, Pandas, NumPy and Scikit-learn.

Experience with data preprocessing, exploratory data analysis,
feature engineering, machine learning model development,
model evaluation and NLP is preferred.

Experience with Generative AI, embeddings, RAG and vector
databases is an additional advantage.
"""

job_embedding = model.encode(
    job_description
).tolist()

job_embedding

results = index.query(
    vector=job_embedding,
    top_k=10,
    include_metadata=True
)

results

for rank,results in enumerate(results["matches"], start=1):
    print(rank,results)



from sentence_transformers import SentenceTransformer
from pinecone import Pinecone, ServerlessSpec
import os


# ============================================================
# 1. PINECONE SETUP
# ============================================================


pc = Pinecone(api_key="pcsk_WLfzy_CnE4YKQTkSqQWEpon7myzzD3FZLwxwaSW9zQgFbmcTH9iR6ezbJL1jbha4FtAcj")

INDEX_NAME = "resume-ranking"

# Free embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Check embedding dimension
print("Embedding dimension:", model.get_sentence_embedding_dimension())


# ============================================================
# 2. CREATE PINECONE INDEX
# ============================================================

existing_indexes = [index["name"] for index in pc.list_indexes()]

if INDEX_NAME not in existing_indexes:

    pc.create_index(
        name=INDEX_NAME,
        dimension=384,          # all-MiniLM-L6-v2 dimension
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )

index = pc.Index(INDEX_NAME)


# ============================================================
# 3. 10 RESUMES
# ============================================================

resumes = [

    {
        "id": "resume_1",
        "name": "Rahul Sharma",
        "text": """
        Rahul Sharma is a Data Scientist with 2 years of experience.
        Skilled in Python, Pandas, NumPy, Scikit-learn, SQL,
        Machine Learning, Deep Learning and Natural Language Processing.
        Experienced in building classification, regression and clustering
        models. Worked with Random Forest, Logistic Regression, XGBoost,
        CNN and NLP models. Experience with data preprocessing,
        exploratory data analysis, feature engineering and model evaluation.
        """
    },

    {
        "id": "resume_2",
        "name": "Priya Singh",
        "text": """
        Priya Singh is a Software Developer with 3 years of experience.
        Strong knowledge of Java, Spring Boot, REST APIs, MySQL,
        Git and Docker. Experienced in backend application development,
        microservices and database management. Familiar with AWS and
        CI/CD pipelines.
        """
    },

    {
        "id": "resume_3",
        "name": "Vilas Kumar",
        "text": """
        Vilas Kumar is an AI and Machine Learning graduate with skills
        in Python, Machine Learning, Deep Learning, SQL, Pandas,
        NumPy and Scikit-learn. Worked on machine learning projects
        involving data preprocessing, exploratory data analysis,
        feature engineering, model training and evaluation.
        Experience with NLP, Generative AI, RAG, embeddings,
        vector databases and MLflow.
        """
    },

    {
        "id": "resume_4",
        "name": "Arjun Patel",
        "text": """
        Arjun Patel is a Data Analyst with 2 years of experience.
        Skilled in SQL, Excel, Power BI, Tableau, Python and Pandas.
        Experienced in dashboard creation, business reporting,
        data visualization, KPI analysis and exploratory data analysis.
        Strong analytical and communication skills.
        """
    },

    {
        "id": "resume_5",
        "name": "Sneha Reddy",
        "text": """
        Sneha Reddy is a Machine Learning Engineer with 3 years
        of experience. Skilled in Python, TensorFlow, PyTorch,
        Scikit-learn, NLP, Computer Vision and Deep Learning.
        Developed neural networks, image classification systems
        and NLP applications. Experience deploying ML models
        using Docker and cloud platforms.
        """
    },

    {
        "id": "resume_6",
        "name": "Karthik Rao",
        "text": """
        Karthik Rao is a Cloud Engineer with 4 years of experience.
        Skilled in AWS, EC2, S3, Lambda, Docker, Kubernetes,
        Terraform and Linux. Experienced in cloud infrastructure,
        deployment automation, monitoring and CI/CD pipelines.
        Strong knowledge of DevOps practices.
        """
    },

    {
        "id": "resume_7",
        "name": "Ananya Gupta",
        "text": """
        Ananya Gupta is a Data Scientist with 1 year of experience.
        Skilled in Python, SQL, Pandas, NumPy, Scikit-learn,
        Machine Learning and statistics. Worked on predictive
        modeling, customer segmentation, regression and classification.
        Experienced in data cleaning, feature engineering and
        model performance evaluation.
        """
    },

    {
        "id": "resume_8",
        "name": "Rohan Mehta",
        "text": """
        Rohan Mehta is a Frontend Developer with 2 years of experience.
        Skilled in HTML, CSS, JavaScript, React.js, Next.js and Git.
        Experienced in building responsive web applications,
        reusable UI components and REST API integrations.
        Strong understanding of frontend development.
        """
    },

    {
        "id": "resume_9",
        "name": "Meera Nair",
        "text": """
        Meera Nair is an AI Engineer with 2 years of experience.
        Skilled in Python, Machine Learning, Deep Learning,
        Generative AI, Large Language Models, NLP, RAG,
        vector databases and embeddings. Built AI applications
        using LangChain, Hugging Face and transformer models.
        Experience with prompt engineering and semantic search.
        """
    },

    {
        "id": "resume_10",
        "name": "Aditya Verma",
        "text": """
        Aditya Verma is a Business Analyst with 3 years of experience.
        Skilled in SQL, Excel, Power BI, business analysis,
        requirements gathering, stakeholder management and
        data visualization. Experienced in analyzing business
        requirements and creating dashboards and reports.
        """
    }
]


# ============================================================
# 4. CREATE EMBEDDINGS
# ============================================================

vectors = []

for resume in resumes:

    embedding = model.encode(
        resume["text"]
    ).tolist()

    vectors.append({
        "id": resume["id"],
        "values": embedding,
        "metadata": {
            "name": resume["name"],
            "resume_text": resume["text"]
        }
    })


# ============================================================
# 5. STORE RESUMES IN PINECONE
# ============================================================

index.upsert(vectors=vectors)

print("\n10 resumes successfully stored in Pinecone.")


# ============================================================
# 6. JOB DESCRIPTION
# ============================================================

job_description = """
We are looking for a Data Scientist.

The candidate should have strong knowledge of Python,
Machine Learning, SQL, Pandas, NumPy and Scikit-learn.

Experience with data preprocessing, exploratory data analysis,
feature engineering, machine learning model development,
model evaluation and NLP is preferred.

Experience with Generative AI, embeddings, RAG and vector
databases is an additional advantage.
"""


# ============================================================
# 7. EMBED JOB DESCRIPTION
# ============================================================

job_embedding = model.encode(
    job_description
).tolist()


# ============================================================
# 8. SEARCH TOP 10 RESUMES
# ============================================================

results = index.query(
    vector=job_embedding,
    top_k=10,
    include_metadata=True
)


# ============================================================
# 9. DISPLAY TOP 10
# ============================================================

print("\n")
print("=" * 70)
print("              TOP 10 MATCHING RESUMES")
print("=" * 70)

for rank, result in enumerate(results["matches"], start=1):

    print(f"\nRank       : {rank}")
    print(f"Name       : {result['metadata']['name']}")
    print(f"Resume ID  : {result['id']}")
    print(f"Similarity : {result['score']:.4f}")

    print("-" * 70)

request= "I need a lightweight laptop for programming"   ## best match 3 results



retail_queries = [
    {
        "query": "Show me men's running shoes under ₹3000",
        "category": "Men's footwear",
        "attributes": "running shoes, price below ₹3000"
    },
    {
        "query": "I need a black formal shirt for office",
        "category": "Men's clothing",
        "attributes": "formal shirt, black, office"
    },
    {
        "query": "Find laptops with at least 16GB RAM",
        "category": "Electronics",
        "attributes": "laptop, RAM >= 16GB"
    },
    {
        "query": "Show me smartphones under ₹20000 with a good camera",
        "category": "Electronics",
        "attributes": "smartphone, price below ₹20000, good camera"
    },
    {
        "query": "I want a red dress for women",
        "category": "Women's clothing",
        "attributes": "dress, red"
    },
    {
        "query": "Find wireless headphones with noise cancellation",
        "category": "Electronics",
        "attributes": "wireless headphones, noise cancellation"
    },
    {
        "query": "Show me cotton t-shirts below ₹1000",
        "category": "Men's clothing",
        "attributes": "cotton t-shirt, price below ₹1000"
    },
    {
        "query": "I need a waterproof backpack for college",
        "category": "Bags",
        "attributes": "backpack, waterproof, college"
    },
    {
        "query": "Find running shoes for women",
        "category": "Women's footwear",
        "attributes": "running shoes"
    },
    {
        "query": "Show me 55 inch 4K smart TVs",
        "category": "Electronics",
        "attributes": "TV, 55 inch, 4K, smart"
    },
    {
        "query": "I need a microwave oven under ₹12000",
        "category": "Home appliances",
        "attributes": "microwave oven, price below ₹12000"
    },
    {
        "query": "Find skincare products for dry skin",
        "category": "Beauty",
        "attributes": "skincare, dry skin"
    },
    {
        "query": "Show me men's watches under ₹5000",
        "category": "Accessories",
        "attributes": "men's watch, price below ₹5000"
    },
    {
        "query": "I need a lightweight laptop for programming",
        "category": "Electronics",
        "attributes": "laptop, lightweight, programming"
    },
    {
        "query": "Find kitchen mixer grinders below ₹4000",
        "category": "Kitchen appliances",
        "attributes": "mixer grinder, price below ₹4000"
    },
    {
        "query": "Show me children's school bags",
        "category": "Kids",
        "attributes": "school bag, children"
    },
    {
        "query": "I want Bluetooth speakers with long battery life",
        "category": "Electronics",
        "attributes": "Bluetooth speaker, long battery"
    },
    {
        "query": "Find comfortable jeans for men under ₹2000",
        "category": "Men's clothing",
        "attributes": "jeans, comfortable, price below ₹2000"
    },
    {
        "query": "Show me face wash for oily skin",
        "category": "Beauty",
        "attributes": "face wash, oily skin"
    },
    {
        "query": "I need a fitness smartwatch with heart-rate monitoring",
        "category": "Electronics",
        "attributes": "fitness smartwatch, heart-rate monitoring"
    }
]



query = "I need a lightweight laptop for programming"



for i, item in enumerate(retail_queries):
    text = f"{item['query']} | {item['category']} | {item['attributes']}"

    embedding = model.encode(text).tolist()

    index.upsert(
        vectors=[
            {
                "id": f"retail-{i}",
                "values": embedding,
                "metadata": {
                    "query": item["query"],
                    "category": item["category"],
                    "attributes": item["attributes"]
                }
            }
        ]
    )

query_embedding = model.encode(query).tolist()

results = index.query(
    vector=query_embedding,
    top_k=3,
    include_metadata=True
)

for i, match in enumerate(results["matches"], 1):
    print(f"Rank {i}")
    print(f"Score: {match['score']:.4f}")
    print(f"Query: {match['metadata']['query']}")
    print(f"Category: {match['metadata']['category']}")
    print(f"Attributes: {match['metadata']['attributes']}")
    print("-" * 50)

